### ISSUE TITLE
Добавить ссылки на инструкции по подписке на календарь

### ISSUE THREAD

**Issue by pavsmk** [web-standards-ru/calendar#12]
Я ни разу не подписывался на календари. Поэтому не сразу понял как это сделать. И искал инструкцию в Readme, но ее нет.
Нагуглив нашел как это сделать на macOS – [инструкция](https://support.apple.com/ru-ru/HT202361).
Еще нашел для Google Календарь, но данный не проверял – [инструкция](https://support.google.com/calendar/answer/37100)
Возможно, я не один такой, поэтому можно сразу в readme добавить

**Comment by pepelsbey** [comment]
Спасибо, добавим!
