### ISSUE TITLE
Время начала сдвинуто на 3 часа вперёд

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/calendar#15]
![image](https://user-images.githubusercontent.com/105274/29211039-4aa54712-7e9f-11e7-9ff4-143942ede2f9.png)

Когда добавляешь календарь через Google Calendar, то время начала сдвигается на 3 часа вперёд. Есть подозрение, что нужна какая-то компенсация по GMT или вроде того.

**Comment by pepelsbey** [comment]
![image](https://user-images.githubusercontent.com/105274/29211089-97aedfc8-7e9f-11e7-9fe8-cd819bb3c2e9.png)

Но если добавить просто так в локальный календарь, то никакого сдвига нет :|

**Comment by Avol-V** [comment]
Это действительно так при добавлении по адресу.  
Вот обсуждение: https://stackoverflow.com/questions/23963459/importing-ics-into-google-calendar-with-correct-timezone

Насколько я понимаю, самое надёжное — добавлять в UTC с «Z».

**Comment by pepelsbey** [comment]
@Avol-v, сделаешь пулреквест? Попробуем, как работает

**Comment by pepelsbey** [comment]
Исправлено в #18 великолепным @Avol-V :)
