### ISSUE TITLE
Krasnodar Frontend Meetup #4

### ISSUE THREAD

**Issue by neonick** [web-standards-ru/calendar#246]
Проводим уже четвертый краснодарский митап по фронтенду, в этот раз будет 5 докладов (уже прям мини-конференция).

В этот раз:
- типизация в js
- как починить Redux
- перфоманс анимаций
- композитные слои и отрисовка
- что разработчик должен знать про дизайн

Кроме этого у нас футболки сообщества за классные вопросы и буккроссинг технической литературы.

https://krddevdays.timepad.ru/event/851590/

**Comment by pepelsbey** [comment]
А пулреквест? )

**Comment by neonick** [comment]
Уже в мастере, кто-то добавил :) я просто добавил инфу :)

**Comment by pepelsbey** [comment]
Гм, это странное место для инфы. Если всё это есть на Таймпаде, то мы прочитаем.

**Comment by pepelsbey** [comment]
Пулреквеста с событием в календаре более чем достаточно. Пинговать «а вы точно не забудете?» тоже не стоит.

**Comment by langovoi** [comment]
В итоге даже после пинга никто так и не анонсировал, а мероприятие уже в эту субботу.

**Comment by pepelsbey** [comment]
Ну и раз уж [пошло недовольство](https://twitter.com/krddevdays/status/1069569290729385984), предлагаю обсудить здесь же:

> Событие в календаре с 18 ноября (причём там было неверное название, как приняли PR совершенно не понятно), но анонса так и не было, а уже в эту субботу мероприятие.
И после этого вы говорите, что мы вам события не приносим в календарь.

Мне даже неловко это писать. Но всё же: календарь сделан для того, чтобы люди подписывались на него в своих приложениях и следили за событиями. Мы также используем его для рубрики «События» в подкасте. Никаких гарантий появления в выпуске мы не даём. Да, событие может оказаться в календаре, а потом не прозвучать в выпуске. Так бывает.

Пулреквест с неправильным названием отправил какой-то ваш активист. Почему приняли? Потому, что так работает календарь. Мы проверяем только корректность форматирования и подходящую тематику события. Если событие какое-то новое — смотрим, читаем внимательно. Ваше — очередное, принималось быстрее обычного. Хотите, чтобы было корректно — отправляйте событие в календарь первыми, как только есть дата и хотя бы какая-нибудь страницы.

**Comment by pepelsbey** [comment]
> В итоге даже после пинга никто так и не анонсировал, а мероприятие уже в эту субботу.

Я себя чувствую провинившимся сотрудником на зарплате или автором паблика, которому заплатили за рекламу, а он не сделал, что обещал. Ребята, это огромная работа раз в неделю в свободное время. Подумайте дважды, прежде чем требовать что-то в следующий раз.

**Comment by langovoi** [comment]
> Да, событие может оказаться в календаре, а потом не прозвучать в выпуске. Так бывает.

Цитата из 146 выпуска подкаста:

> в Краснодаре не так много мероприятий происходит, там происходят, но не такие на слуху, по крайней мере эти мероприятия не приносят в календарь.

Проблема в том, что сначала вы публично говорите, что в Краснодаре ничего не происходит, что события в календарь не приносят. Хотя до этого мы всегда присылали PR, и вы нас анонсировали, за что большое спасибо.

> Пулреквест с неправильным названием отправил какой-то ваш активист.

Не хочу ничего плохого про этого человека говорить, он молодец, что вперед нас добавил событие в календарь, хоть и с ошибкой. Его мы не знаем вообще.

Но может как-то стоит проверять информацию, которую присылают?
Там по ссылке сразу написано `Krasnodar Frontend: Meetup #4`, а не `Krasnodar Dev Days #4`.

> Ребята, это огромная работа раз в неделю в свободное время. Подумайте дважды, прежде чем требовать что-то в следующий раз.

Никто ничего не требует, наоборот, думаю, тебе все благодарны за деятельность в свободное время, но просто ситуация выглядит двояко.

Например WSD и CSS-Minsk-JS анонсируются по 2-3 раза подряд до конференции, а нашу конференцию в сентябре анонсировали всего один раз. Выглядит странно, не правда ли?

В общем, хочется донести одну мысль – не стоит говорить "приносите события в календарь" без ремарки на то, что события все же может и не быть упомянутым.

Для нас, думаю как и для многих региональных мероприятий, ваш подкаст служит площадкой для анонсирования, которая сильно помогает, но вот такие ситуации сильно выбивают из колеи, хотя понятное дело, что требовать с тебя что-то мы не можем и ты никому ничего не должен.

**Comment by pepelsbey** [comment]
> Например WSD и CSS-Minsk-JS анонсируются по 2-3 раза подряд
> А нашу конференцию в сентябре анонсировали всего один раз.

Ну то есть всё же требуете. Справедливости, равного эфирного времени. Это не выборы президента, а мы не Первый канал, чтобы требовать такого. Я рассказываю больше и равёртуто тогда, когда мне есть что сказать. Когда я людей знаю, когда бывал на конференции.

Ну вот опять: мне приходится оправдываться. Я _должен_ всех упомянуть. Дичь какая-то.

**Comment by langovoi** [comment]
> Ну вот опять: мне приходится оправдываться. Я должен всех упомянуть. Дичь какая-то.

Не нужно оправдываться, я же не прекращу помогать тебе делать новый сайт из-за этого, просто мы пытаемся дать тебе фидбек, может не совсем приятный, может не в той форме, в который ты привык его получать.

Мы не ждем от тебя каких-то действий, это твое детище и тебе решать каким ему быть, мы просто приносим свое мнение, что нам кажется не так. Такой вот open-source :-)

**Comment by pepelsbey** [comment]
Короче: календарь — это календарь для тех, кто добавил его себе. События в подкасте — это авторский обзор событий на основе календаря. Если автор не знает, не помнит или не считает нужным что-то включать в обзор — очень жаль, но именно так и прозвучит. Потому, что это импровизация под запись и _авторский_ обзор. Механически зачитывать словарь без мнений и впечатлений никто не будет.

> Мы не ждем от тебя каких-то действий

Почему я тогда снова чувствую давление? Митап уже в субботу, а вы молчите! Фига.

**Comment by langovoi** [comment]
> Почему я тогда снова чувствую давление?

К сожалению на этот вопрос я не знаю ответа, я максимально постарался обьяснить что мы тут не ругаться пришли, а обратную связь донести.

**Comment by langovoi** [comment]
> С кучей людей в копии и от аккаунта конференции — что отдельно доставляет.

Куча людей – там полностью к месту, кроме одного человека, а в остальном это продолжение треда, который начался еще после 146 выпуска.
Про аккаунт сообщества – не вижу никаких проблем с этим.

> Это не обратная связь, что критика нашей плохой работы. 

В моем понимание `критика = обратная связь`.

Твое видение календаря и подкаста мы поняли и впредь будем меньше полагаться на помощь в виде анонса, так как теперь знаем все тонкости.

Предлагаю не мусолить тему, если тебе больше ничего донести до нас.

**Comment by pepelsbey** [comment]
Надеюсь вы продолжите добавлять события в календарь. Я только прошу не требовать и не упрекать, это обижает и демотивирует делать и без этого непростое дело.

**Comment by langovoi** [comment]
Полностью согласны и не коем случае не хотели вызвать такие эмоции, а приносить события в календарь не броси.
