### ISSUE TITLE
Не добавляется ссылка

### ISSUE THREAD

**Issue by Gurylev** [web-standards-ru/calendar#25]
В добавляемых мероприятиях есть пункт `link`, но в подписке гугл календарём ссылок на мероприятия не видно.

![frontend calendar - event details](http://grlv.ru/i/lct6s.png)

В маковском приложении «календарь» ссылку видно, так что, кажется, это баг скорее гугл календаря. Но я пользуюсь именно гугл календарём. И, думаю, не я один.

Возможно, имеет смысл добавлять ссылку в `description` события?

**Comment by pepelsbey** [comment]
Проверил форумы Google Calendar: на поддержку поля URL они плевали, так что и правда придётся ссылку класть в описание. Проблема, правда, в том, что из календаря описание не видно и нужно проходить в событие, чтобы кликнуть. Но зато macOS делает кликабельной ссылку в описании.

Стандарты.

**Comment by pepelsbey** [comment]
В общем: нужно заменить
```
URL:https://yandex.ru
```
на
```
DESCRIPTION:https://yandex.ru
```

**Comment by pepelsbey** [comment]
Кто смелый для PR? :)

**Comment by Avol-V** [comment]
Да, похоже Google Calendar просто не поддерживает поле.

Немного поискал, вот здесь человек вопрашал в пустоту — https://productforums.google.com/forum/#!topic/calendar/rHDYyUdA6iw, — а здесь спашивал, как добавлять в description, чтобы было кликабельно (видимо, ещё и с эти могут быть проблемы), а заодно и про отдельное поле спросил — https://productforums.google.com/forum/#!topic/calendar/zEhTxqbxDPY

Наверное нужно добавить в описание, но при этом:

- Поле URL оставить, для приложений, которые понимают его (хотя возможная проблема — дважды ссылка, что может быть не симпатично).
- Нужно что-то ещё добавить в описание, чтобы там не была одна сиротливая ссылка (ну или хотя-бы просто подписать, вроде «Подробнее о мероприятии: …»).

**Comment by Avol-V** [comment]
@pepelsbey есть мысль, что может всё-таки не заменить, а добавить? (см. пункты выше)

**Comment by pepelsbey** [comment]
Мне довелось пока проверить три приложения: Google, Fantastical и Calendar (macOS) — все они делают кликабельной ссылку в описании. Последние два понимают ссылку в URL. Какие есть причины, чтобы дублировать её? Те, кто понимают URL, получат страшноватое дублирование.

По-моему лаконичная ссылка без лишних слов в описании будет достаточно понятной. Говорить, что это страница события или что подробности там — лишее, это кажется очевидным. Куда ещё может вести ссылка? Особенно когда в адресе чаще всего есть название события: в домене или дальше.

**Comment by Avol-V** [comment]
Ну возможно специальная ссылка более удобна в использовании, а текст я предлагал добавить, чтобы дублирование было не таким страшным.

Но можно и просто в `description` исправить `url` без лишних сложностей :)

**Comment by Avol-V** [comment]
Исправил. Посмотрим как выглядит, когда календарь обновится :)

**Comment by pepelsbey** [comment]
Проверил ещё в Window Calendar: там тоже всё плохо и URL нет (

**Comment by Gurylev** [comment]
Вот это скорость! Спасибо огромное за такую быструю реакцию!
Зашёл снова в гугл календарь. Ссылок всё ещё не видно 😞  Попробовал отписаться от календаря и подписаться заново - не помогло. Может быть, я ещё какой-то кэш упускаю?

**Comment by pepelsbey** [comment]
Гугл может до 12 часов с кэшем тупить, насколько я понимаю. [По факту](https://raw.githubusercontent.com/web-standards-ru/calendar/master/dist/calendar.ics) `URL` уже нет, есть `DESCRIPTION`.

**Comment by Avol-V** [comment]
Да, отписка от календаря не помогает — кэш обновляется только спустя время. Мне, тестируя, приходилось просто файл календаря называть каждый раз по новому, чтобы это обойти.

**Comment by Gurylev** [comment]
Не знаю, как вы тестируете фичи, это ж кошмар! Спасибо за разъяснения, кэш сбросился, всё хорошо! И спасибо за доработки про details ещё раз :)
