### ISSUE TITLE
Время начала и окончания в многодневном мероприятии

### ISSUE THREAD

**Issue by Gurylev** [web-standards-ru/calendar#28]
Сейчас, когда мероприятие идёт несколько дней, оно автоматически выглядит в календаре как мероприятие на целый день, даже если такой галочки не стоит.

![Пример многодневного мероприятия](http://grlv.ru/i/7or7p.png)

Есть предложение на нашей стороне автоматически бить такие мероприятия на несколько с пометкой в стиле (2 day). Тогда для каждого дня можно было бы видеть время начала и время окончания в календаре.

Ведь по факту фронтнд-мероприятия это не camp-лагерь, где мероприятие однажды начинается и однажды заканчивается. Чаще всего после окончания первого дня нужно/можно куда-то ещё пойти пить/ночевать. Было бы круто видеть из календаря это промежуточное время сразу.

**Comment by Avol-V** [comment]
Затрагивалось при обсуждении в #9 — возникает вопрос, как хранить время для многодневных мероприятий, ведь нередко оно различается в разные дни (как минимум, из-за открытия / закрытия).

Поэтому, чтобы не усложнять формат, было сделано так, что многодневные мероприятия всегда считаются «на весь день».

Да и нагляднее в календаре, что мероприятие многодневное, когда оно отображается сплошным блоком.

**Comment by pepelsbey** [comment]
Не вижу большой ценности в том, чтобы в принципе задавать время начала и конца однодневных конференций. Если конференция на день — день всё равно потерян. Если это митап на вечер или нод-скул днём — время важно.

Насколько я понимаю, мы сейчас игнорируем время начала и конца, если мероприятие больше, чем на день.

**Comment by Gurylev** [comment]
Возможно, вы недостаточно плотно планируете своё время, поэтому не понимаете проблемы.

Представим:
Я вот поеду в Москву на двухдневный HolyJS в декабре, а вечером после первого дня встречусь со знакомым по работе. Встреча с ним у меня тоже запланирована в календаре.
Днём на конфу, а вечером на деловую встречу - нормальный паттерн, мне кажется. Весь день не обязательно терять, особенно при посещении другого города.

Когда есть мероприятие, отмеченное на весь день и в этот же день ещё одно мероприятие только на вечер, то замечательный Meekan Scheduling пишет мне «у тебя тут два мероприятия пересекаются, кажется, какое-то надо перенести». Это и есть та проблема, о которой я создал ишью.

Ну, я к тому, что это всё мешает планированию оставшегося дня. Мешает не нам, создателям календаря, а тем, кто юзать его будет.

**Comment by Avol-V** [comment]
Отдельные файлы руками точно не нужно делать — в коде та это всяко можно порезать как угодно. Вот только есть сомнения — насколько это нужно.

Мне тоже кажется, что здесь больше про информирование о мероприятиях — и «растяжка» на несколько дней выглядит информативнее именно в общем обзорном плане.

Этот календарь ведь содержит не личный перечень мероприятий для посещения — не все из них вообще будут интересны каждому. И событие на весь день выглядит именно так — фоново, — очень странно, что какой-то софт учитывает коллизии с подобными событиями.

Мне кажется, что если нужно вписать событие в свой график, то его уже нужно добавить самостоятельно со своими временными рамками, которые могут и не совпадать с временем начала/окончания самого мероприятия.

**Comment by Gurylev** [comment]
Ну ок. 
> если нужно вписать событие в свой график, то его уже нужно добавить самостоятельно со своими временными рамками, которые могут и не совпадать с временем начала/окончания самого мероприятия
Так обычно и делаю) Хотел «из коробки». Но, наверное, это действительно ненужное усложнение этого проекта.
