### ISSUE TITLE
Сделать автосборку

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/calendar#45]
Сейчас приходиться пулить локально и потом делать `npm start`, а хотелось бы на Тревисе собирать и арсинкать прямо живой календарь без редиректов на `web-standards.ru/calendar.ics`.

@h4 сможешь завести?

**Comment by h4** [comment]
В течение недели сделаю

**Comment by h4** [comment]
Вот эта строчка в конфиге мне что-то не нравится, возможно, что перебить permanent redirect не получится.

```conf
rewrite /calendar.ics https://raw.githubusercontent.com/web-standards-ru/calendar/master/dist/calendar.ics permanent;
```

**Comment by pepelsbey** [comment]
Так если убрать из конфига — всё равно не перебьём?

**Comment by h4** [comment]
Я не знаю, как работает клиентская библиотека в гугл-календаре и прочих. Браузер вроде как 301-й редирект запоминает и сразу ломится на гитхаб.

В любом случае, на гитхабе `dist/calendar.ics` останется, если мы решим доделать вариант со сборкой и пушем через @wsd-bot

**Comment by h4** [comment]
@pepelsbey запилено.

**Comment by pepelsbey** [comment]
Спасибо :)
