### ISSUE TITLE
Хранить одно мероприятие в одном файле

### ISSUE THREAD

**Issue by ezhlobo** [web-standards-ru/calendar#5]
Я думаю следить за мероприятиями в одном файле гораздо тяжелее, чем получить их список в отдельной директории.

Также не придется сортировать их по дате, если указывать ее в названии файла. Гитхаб отсортирует вместо нас.

Что думаете об этом?

//CC @pepelsbey

**Comment by Semigradsky** [comment]
Звучит здраво, будет легче PR принимать — никаких конфликтов.

**Comment by pepelsbey** [comment]
Согласен. Осталось только придумать именование файлов, которое позволит их удобно сортировать. Сейчас поколдую и предложу.

**Comment by ezhlobo** [comment]
@pepelsbey как вариант:
```
год-месяц-день-час-название
```

Или проще
```
год-месяц-день-название
```

И уже ориентироваться можно будет легче.

**Comment by pepelsbey** [comment]
[Так и сделал](https://github.com/web-standards-ru/calendar/tree/master/events)

**Comment by ezhlobo** [comment]
@pepelsbey выглядит хорошо ;). Я закрываю ишью
