### ISSUE TITLE
Добавить формат события

### ISSUE THREAD

**Issue by webstartsev** [web-standards-ru/calendar#526]
Предлагаю добавить новое поле в котором будет формат события: online || offline.
Если формата нет, то по умолчанию считается offline, для прошлых событий.

**Comment by webstartsev** [comment]
#527 pr

**Comment by pepelsbey** [comment]
Формат-то добавим, а как это отразится на самом событии в календаре?

Плюс мне кажется, что лучше использовать булевы значения. То есть:

```yml
time: hh:mm-hh:mm
city: city
link: url
online: true
```
В отстутствии ключа `online` (в предыдущих и будущих), можно приводить его к `false`. Но тут опять вопрос «и что»? Нужно придумать какую-то пометку в описании или что-то вроде того. Город я бы продолжал требовать для тайм-зон, то есть писать `city: online` не стоит.

**Comment by webstartsev** [comment]
Самое простое: добавлять в название - online. Визуально будет понятно.

**Comment by Semigradsky** [comment]
Если есть ключ `online: true`, то добавлять к названию

Tver.io JavaScript Meetup [Online]

или

[Online] Tver.io JavaScript Meetup
