### ISSUE TITLE
Обновить зависимости и починить сборку

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/calendar#528]
Было

```json
  "devDependencies": {
    "geo-tz": "^3.3.3",
    "ical-generator": "^0.2.9",
    "js-yaml": "^3.7.0",
    "moment-timezone": "^0.5.13",
    "mutex-js": "^1.1.5",
    "node-geocoder": "^3.22.0",
    "pify": "^3.0.0",
    "yaml-lint": "^1.2.3"
  }
```

Стало

```json
  "devDependencies": {
    "geo-tz": "^5.1.0",
    "ical-generator": "^1.9.3",
    "js-yaml": "^3.13.1",
    "moment-timezone": "^0.5.13",
    "mutex-js": "^1.1.5",
    "node-geocoder": "^3.22.0",
    "pify": "^5.0.0",
    "yaml-lint": "^1.2.3"
  }
```

При «стало» скрипт `generate` валится с ошибкой. Судя по всему, поменялся API пакета [node-geo-tz](https://github.com/evansiroky/node-geo-tz), но правка `GeoTz.tz()` на `GeoTz()` решает только часть проблемы, ошибки продолжают сыпаться.

**Comment by Semigradsky** [comment]
У `node-geo-tz` изменилось апи - теперь возвращает массив найденных таймзон. Сделал, чтобы возвращало первый из найденных.

Проверил `dist/calendar.ics` - после обновления зависимостей генерирует такой же как и раньше.
