### ISSUE TITLE
Фильтровать экранирование при генерации

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/calendar#54]
Так вышло, что все очень любят анлоязычную традицию писать номера вот так `#1`, а `#` это комментарий в YAML, поэтому проще всего писать `\#` и не париться. Но этот слэш пролазит в экспорт — вот бы его фильтровать при генерации.

**Comment by pepelsbey** [comment]
@Avol-V поможешь? Кажется, что это совсем мелочь.

**Comment by Avol-V** [comment]
Да, видел эту проблему по коммитам, предполагал, что придётся что-нибудь с этим делать в коде :)

Странно, что это ни как не решается модулем работы с YAML, но несложно и после него подправить — постараюсь сегодня сделать.

**Comment by Avol-V** [comment]
Решил проблему — в созданном после Travis файле слэшей уже нет.

**Comment by pepelsbey** [comment]
Спасибо! :)
