### ISSUE TITLE
Веб страница с ближайшими событиями

### ISSUE THREAD

**Issue by nin-jin** [web-standards-ru/calendar#565]
На [сайте у вас](https://web-standards.ru/) эта страница пока не реализована. Запилил пока у нас вывод последних событий: https://piterjs.org/#others
Из неудобства - в [JSON](https://web-standards.ru/calendar.json) прилетают все события за последние 4 года. Может их как-то хотя бы по годам разбивать?

**Comment by pepelsbey** [comment]
Попыток сделать страницы с календарями на основе нашего фида — не счесть. Мы для этого и сделали JSON. Кажется, что это задача сервиса работать с данными после получения, а не нам менять формат данных.

**Comment by nin-jin** [comment]
Может стоит добавить ссылки на них в ридми?
В том-то и дело, что у нас чисто клиентское приложение.

**Comment by pepelsbey** [comment]
Добавлять ссылки в ридми на чьи-то эксперименты, которые редко поддерживаются и развиваются — не хочется. Иначе будет казаться, что мы рекомендуем их как способ просмотра календаря. Пока у нас нет своей страницы на сайте для этого, у нас этот календарь интегрируется в обычные календари и это главный юзкейс.

Фид всего календаря сейчас весит 130 КБ (или 20 КБ в гзипе). Кажется, что это не слишком тяжело для клиентского приложения, особенно если это не код для отрисовки интерфейса, а данные.
