### ISSUE TITLE
Падает сборка

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/calendar#618]
- `node -v` v14.16.1
- `npm -v` 6.14.13

```
npm run build
…
������\x00\x00\x00\x1C\x002\x000\x002\x000\x00-\x001\x000\x00-\x001\x005\x00-\x00d\x00y\x00m\x00a\x00n\x00i\x00c\x00-\x00t\x00a\x00l\x00k\x00s\x00.\x00y\x00m\x00lIlocblob\x00\x00\x00\x10����������������\x00\x00\x00(\x002\x000\x002\x000\x00-\x001\x000\x00-\x001\x005\x00-\x00f\x00a\x00c\x00e\x00b\x00o\x00o',
    position: 0,
    line: 0,
    column: 0,
    snippet: ' 1 | \n-----^\n 2 | \n 3 | '
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `node scripts/generateCalendar.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pepelsbey/.npm/_logs/2021-06-16T14_02_27_635Z-debug.log
```

**Comment by pepelsbey** [comment]
Пока только вернули город в одно из событий. Но всё равно не помогает:

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/105274/122233945-1e781f00-cec5-11eb-8a58-faca215f0ef9.png">

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/105274/122233869-1324f380-cec5-11eb-892e-e34f95a5e313.png">

**Comment by Zulcom** [comment]
По ошибке не понятно в чём её суть, но у меня она почему-то собирается в обоих из случаев со скриншотов

**Comment by pepelsbey** [comment]
Склонировал начисто — собралось 🤔

**Comment by Zulcom** [comment]
Даже без фикса ical?

**Comment by pepelsbey** [comment]
Это чёртова мистика, действительно [починилось](https://github.com/web-standards-ru/calendar/commit/ef96478d5557dfe008970574a657c4d567647dba). Просто удалил старый реп и завёл новый :)

Спасибо!
