### ISSUE TITLE
Нельзя подписаться на календарь (ошибка валидации)

### ISSUE THREAD

**Issue by totfront** [web-standards-ru/calendar#663]
Iphone Xs Max / Software Version 15.5

![photo_2022-07-13 12 04 34](https://user-images.githubusercontent.com/42805085/178708245-2885a28e-b2e3-4700-84db-58b1adf1a1e7.jpeg)
![photo_2022-07-13 12 04 32](https://user-images.githubusercontent.com/42805085/178708269-7b08eefc-e5bb-42ef-8eda-6a1a2ebcf274.jpeg)

Адрес календаря копировал из мануала по подписке.

*заработало, когда скопировал ссылку из девтулзов. Может, сразу в мануале правильный путь `https://web-standards.ru/calendar.ics` указать, так как плейсхолдер в поле ввода не подсказывает про **https://**?

**Comment by pepelsbey** [comment]
Поправил, спасибо!

https://github.com/web-standards-ru/calendar/commit/d430bcd8bf5b47f985e6ce921a1fe47d72adb887
