### ISSUE TITLE
Опциональные поля «время начала» и «время конца»

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/calendar#9]
Если они не указаны, то можно делать «на целый день», как в #8. Осталось понять, в каком формате указывать временные зоны, чтобы на такой календарь можно было и правда положиться. В принципе, сдвиг можно вычислять по `city, country`, но это нетривиальная задача.

**Comment by Avol-V** [comment]
Провёл небольшое исследование с экспериментами — часовой пояс вполне корректно определяется использованием геокодера для поиска координат по строке `city, country`, с последующим определением названия зоны по IANA используя базу OpenStreetMap (проверил все текущие сочетания, которые есть в календаре).

Для первого можно воспользоваться **node-geocoder** с провайдером данным openstreetmap, чтобы не привязываться в API ключам. Для второго — **node-geo-tz**. Ещё здесь нужно будет сделать кэширование, чтобы дёргать сеть только для новых сочетаний страна/город.

Могу попробовать реализовать всё это в коде, но есть вопросы касательно того, как в yml должно быть представлено время.

Можно хранить всё просто `time: hh:mm-hh:mm`, но если событие идёт несколько дней с разным временем начала/завершения? Или это можно не брать в расчёт?  
Обязательно ли время завершения, или оно может быть упущено?

**Comment by pepelsbey** [comment]
Я бы оставил добавление времени на усмотрение добавляющих. Можно даже рекомендовать: если ваша конференция длится больше два дня и больше, то добавлять время смысла не имеет. А если это митап на вечер — имеет ещё как.

**Comment by pepelsbey** [comment]
Или ввести правило: если дата — диапазон, то не учитывать время при генерации, а просто делать два полных дня. Так даже лучше, по-моему.

**Comment by pepelsbey** [comment]
Исправлено в #20 великолепным @Avol-V :)

**Comment by pepelsbey** [comment]
![image](https://user-images.githubusercontent.com/105274/29271061-4f0fd80c-8102-11e7-876d-958c0aa62f4a.png)
